### ISSUE TITLE
Librehardwareservice.exe cannot be started

### ISSUE THREAD

**Issue by LRF520** [epinter/LibreHardwareService#1]
Librehardwareservice.exe cannot be started. How do you want to start this librehardwareservice.exe?

How can I get JSON data?

![20220831_112720](https://user-images.githubusercontent.com/58470642/187586425-b64447c7-71b1-44d2-a979-fcbaab0a2f1d.jpg)

![image](https://user-images.githubusercontent.com/58470642/187586626-85995eb4-4358-4938-b824-934e64ba1e0c.png)

**Comment by epinter** [comment]
Hi !
LibreHardwareService is a service (can't be started without install it) that writes a JSON data in a shared memory every second, this JSON contains sensors from LibreHardwareMonitor library. I created this to use with https://github.com/epinter/rainmeter-lhws (which uses https://github.com/epinter/lhwservice).

In a development environment, if you run "LibreHardwareService.exe --install" it will install the service on your windows machine.

**Comment by LRF520** [comment]
Oh, what a pity. I think outputting JSON data on the command line can help many people. Thank you!
